### PR TITLE
Fix: bug on expected input fields check

### LINKED ISSUE #55: Bug: add missing payload to pass expected fields validation check backend
**Describe the bug**
Backend code has been modified by adding the expected fields validation check which means if frontend payload does not match request body, it will response with error code Bad reequest (400)

**To Reproduce**
1. Go to Register and register as a new user with only one availability checked ("available as mentor" or "need mentoring", but not both)
2. Submit the form and see the error response below:
"Unexpected input is detected. Please check your input to make sure only approved fields are to be submitted."

**Expected behavior**
No error message should be returned since availability options are optional.

**Screenshots**
Screen Shot 2020-07-27 at 1 52 31 pm

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version ?

**Additional context**
NA

### PR DESCRIPTION
**Pull request by mtreacy002**
Allow user to have one or more options empty from the availability options (need mentoring or available to mentor) and refactor get data message inside fetch call

### Description

Fixes #55 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Register a new user with only one of the availability option chosen. A successful response will look like below screrenshot:
Screen Shot 2020-07-27 at 2 53 57 pm

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . This PR fix issue that comes from expected input fields validation check on backend where payload is checked against the expected request body.

File: src/register/Register.jsx [hunk 1]
```diff
@@ -21,8 +21,13 @@ export default function Register() {
                     payload[key] = false;
             else
                 payload[key] = value;
-            });
+        });
 
+        if (!("available_to_mentor" in payload))
+            payload["available_to_mentor"] = false;
+        if (!("need_mentoring" in payload))
```
Comment (meenakshi-dhanani) [inline src/register/Register.jsx]: the code in both of these is almost the same. Do you see scope for refactoring? instead of duplicating the code?

File: src/login/Login.jsx [hunk 2]
```diff
@@ -31,7 +31,7 @@ export default function Login() {
                 if (response.status === 200) {
                     login(data, user);
                 }
-                setErrorMessage(data["message"]);
+                setErrorMessage(data.message);
             })
             .catch(() => setErrorMessage("The server is currently unavailable. Try again later"));
```
Comment (ramitsawhney27) [inline src/login/Login.jsx]: Can this error message be a constant and just imported everywhere it's used?

File: src/register/Register.jsx [hunk 3]
```diff
@@ -35,12 +40,11 @@ export default function Register() {
...
         fetch(`${BASE_API}/register`, requestRegister)
             .then(async response => {
-
                 data = await response.json();
-                setResponseMessage(data["message"]);
+                setResponseMessage(data.message);
             })
             .catch(error => {
-                setResponseMessage(data["message"]);
+                setResponseMessage(data.message);
```
Comment (ramitsawhney27) [inline src/register/Register.jsx]: What is the expected output here? if the call fails, and we end up in the catch block, what would data.message be?

File: src/register/Register.jsx (hunk 1 above)
Comment (mtreacy002) [reply src/register/Register.jsx]: I can't see how this is duplicating since there are 2 attributes here that I check and add if not in payload, "need_mentoring" and "available_to_mentor". Maybe tonight you can give me suggestion how to make them more efficient without specifying the attributes need to be created.
Screen Shot 2020-07-31 at 5 32 15 pm

File: src/login/Login.jsx (hunk 2 above)
Comment (mtreacy002) [reply src/login/Login.jsx]: Done. It's now a constant 😁

File: src/register/Register.jsx (hunk 3 above)
Comment (mtreacy002) [reply src/register/Register.jsx]: I've modified the fetch block
Screen Shot 2020-07-31 at 8 59 21 pm

The responseMessage set inside if block (line 45) is if the response is 201, for all other customized responses (400, 409, including 500 that is catched by BIT backend server) will be set as response on line 46. The line 49 for inside catch block is reserved for any unexpected responses such as 500 that is returned when BIT backend server is not running.

Comment (meenakshi-dhanani) [reply src/register/Register.jsx]: @ramitsawhney27 We need to refactor all api calls in one place. But that will be a separate PR.

**Review by meenakshi-dhanani — DISMISSED** [review]

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @ramitsawhney27 and @meenakshi-dhanani . I've resolved merge conflict and force pushed the changes. Can you please re-approve and merge the PR? Thanks

**Review by meenakshi-dhanani — APPROVED** [review]

**Review by ramitsawhney27 — APPROVED** [review]
